# Generated by Django 4.1.3 on 2024-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0002_peopleworks_peopleworkscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleworks',
            name='CreatedBy',
            field=models.CharField(default='Dimoso Junior', max_length=100),
        ),
    ]
